import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer";
import Header from "../components/header/header";
import { ThemeProvider } from "./themeProvider"
import {Toaster}  from "../components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

          <main className="pb-8 min-h-screen bg-background text-foreground break-words leading-6 transition-colors duration-500">
            <Header />
            <div className="px-5 pt-14 mx-auto max-w-3xl">
              <Toaster />
              {children}
            </div>
            <Footer />
          </main>
          </ThemeProvider>
      </body>
    </html>
  );
}